services:
  - type: web
    name: ai-telegram-bot-google
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dummy:app & python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_TOKEN
      - key: GOOGLE_API_KEY
        value: YOUR_GOOGLE_API_KEY